version: '3.7'

services:
  src:
    build: 
      context: .
      dockerfile: ./deploy/rails/Dockerfile
    container_name: src
    restart: always
    env_file: ./deploy/dev.env
    ports:
      - "3000:3000"
    links: 
      - mysql
    volumes:
      - .:/var/www/ror_app
      - /var/www/ror_app/node_modules/
    depends_on: 
      - mysql
    networks:
      static-network:
        ipv4_address: 172.20.128.3
  
  nginx:
    build: 
      context: .
      dockerfile: ./deploy/nginx/Dockerfile
    container_name: nginx
    restart: always
    env_file: ./deploy/dev.env
    links: 
      - src
    ports:
      - "80:80"
    volumes:
      - public:/var/www/ror_app/public
    networks:
      static-network:
        ipv4_address: 172.20.128.1
      
  mysql:
    image: mysql
    container_name: mysql
    env_file: ./deploy/dev.env
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    networks:
      static-network:
        ipv4_address: 172.20.128.2
      
volumes: 
  public:
  .:

networks:
  default:
    driver: bridge
  static-network:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
